version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env  # Loads MONGO_URI from your local .env
    volumes:
      - .:/app  # Sync code for live reload
    restart: unless-stopped
